name: deploy-actions

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    depoly:
        runs-on: ubuntu-latest
        steps:
			### 1
            - name: Checkout source code
              uses: actions/checkout@v3

			### 2
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

			### 3
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

			### 4
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
                  aws-region: ${{ secrets.AWS_S3_REGION }}

			### 5
            - name: Build
              run: npm run build

			### 6
            - name: Deploy to S3
              run: aws s3 sync ./disy s3://ingterior-deployment-bucket/ --delete

			### 7
            - name: Invalidate CloudFront Cache
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
